/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var menudata={children:[
{text:"Main Page",url:"index.html"},
{text:"Namespaces",url:"namespaces.html",children:[
{text:"Namespace List",url:"namespaces.html"},
{text:"Namespace Members",url:"namespacemembers.html",children:[
{text:"All",url:"namespacemembers.html",children:[
{text:"a",url:"namespacemembers.html#index_a"},
{text:"b",url:"namespacemembers_b.html#index_b"},
{text:"c",url:"namespacemembers_c.html#index_c"},
{text:"d",url:"namespacemembers_d.html#index_d"},
{text:"e",url:"namespacemembers_e.html#index_e"},
{text:"f",url:"namespacemembers_f.html#index_f"},
{text:"g",url:"namespacemembers_g.html#index_g"},
{text:"h",url:"namespacemembers_h.html#index_h"},
{text:"i",url:"namespacemembers_i.html#index_i"},
{text:"k",url:"namespacemembers_k.html#index_k"},
{text:"l",url:"namespacemembers_l.html#index_l"},
{text:"m",url:"namespacemembers_m.html#index_m"},
{text:"n",url:"namespacemembers_n.html#index_n"},
{text:"o",url:"namespacemembers_o.html#index_o"},
{text:"p",url:"namespacemembers_p.html#index_p"},
{text:"q",url:"namespacemembers_q.html#index_q"},
{text:"r",url:"namespacemembers_r.html#index_r"},
{text:"s",url:"namespacemembers_s.html#index_s"},
{text:"t",url:"namespacemembers_t.html#index_t"},
{text:"u",url:"namespacemembers_u.html#index_u"},
{text:"v",url:"namespacemembers_v.html#index_v"},
{text:"w",url:"namespacemembers_w.html#index_w"},
{text:"x",url:"namespacemembers_x.html#index_x"},
{text:"y",url:"namespacemembers_y.html#index_y"},
{text:"z",url:"namespacemembers_z.html#index_z"}]},
{text:"Functions",url:"namespacemembers_func.html"},
{text:"Enumerations",url:"namespacemembers_enum.html",children:[
{text:"a",url:"namespacemembers_enum.html#index_a"},
{text:"b",url:"namespacemembers_enum_b.html#index_b"},
{text:"c",url:"namespacemembers_enum_c.html#index_c"},
{text:"d",url:"namespacemembers_enum_d.html#index_d"},
{text:"e",url:"namespacemembers_enum_e.html#index_e"},
{text:"f",url:"namespacemembers_enum_f.html#index_f"},
{text:"g",url:"namespacemembers_enum_g.html#index_g"},
{text:"h",url:"namespacemembers_enum_h.html#index_h"},
{text:"i",url:"namespacemembers_enum_i.html#index_i"},
{text:"k",url:"namespacemembers_enum_k.html#index_k"},
{text:"l",url:"namespacemembers_enum_l.html#index_l"},
{text:"m",url:"namespacemembers_enum_m.html#index_m"},
{text:"n",url:"namespacemembers_enum_n.html#index_n"},
{text:"o",url:"namespacemembers_enum_o.html#index_o"},
{text:"p",url:"namespacemembers_enum_p.html#index_p"},
{text:"q",url:"namespacemembers_enum_q.html#index_q"},
{text:"r",url:"namespacemembers_enum_r.html#index_r"},
{text:"s",url:"namespacemembers_enum_s.html#index_s"},
{text:"t",url:"namespacemembers_enum_t.html#index_t"},
{text:"u",url:"namespacemembers_enum_u.html#index_u"},
{text:"v",url:"namespacemembers_enum_v.html#index_v"},
{text:"w",url:"namespacemembers_enum_w.html#index_w"},
{text:"x",url:"namespacemembers_enum_x.html#index_x"},
{text:"y",url:"namespacemembers_enum_y.html#index_y"},
{text:"z",url:"namespacemembers_enum_z.html#index_z"}]}]}]},
{text:"Classes",url:"annotated.html",children:[
{text:"Class List",url:"annotated.html"},
{text:"Class Index",url:"classes.html"},
{text:"Class Hierarchy",url:"inherits.html"},
{text:"Class Members",url:"functions.html",children:[
{text:"All",url:"functions.html",children:[
{text:"_",url:"functions.html#index__5F"},
{text:"a",url:"functions_a.html#index_a"},
{text:"b",url:"functions_b.html#index_b"},
{text:"c",url:"functions_c.html#index_c"},
{text:"d",url:"functions_d.html#index_d"},
{text:"e",url:"functions_e.html#index_e"},
{text:"f",url:"functions_f.html#index_f"},
{text:"g",url:"functions_g.html#index_g"},
{text:"h",url:"functions_h.html#index_h"},
{text:"i",url:"functions_i.html#index_i"},
{text:"j",url:"functions_j.html#index_j"},
{text:"k",url:"functions_k.html#index_k"},
{text:"l",url:"functions_l.html#index_l"},
{text:"m",url:"functions_m.html#index_m"},
{text:"n",url:"functions_n.html#index_n"},
{text:"o",url:"functions_o.html#index_o"},
{text:"p",url:"functions_p.html#index_p"},
{text:"q",url:"functions_q.html#index_q"},
{text:"r",url:"functions_r.html#index_r"},
{text:"s",url:"functions_s.html#index_s"},
{text:"t",url:"functions_t.html#index_t"},
{text:"u",url:"functions_u.html#index_u"},
{text:"v",url:"functions_v.html#index_v"},
{text:"w",url:"functions_w.html#index_w"},
{text:"x",url:"functions_x.html#index_x"},
{text:"y",url:"functions_y.html#index_y"},
{text:"z",url:"functions_z.html#index_z"}]},
{text:"Functions",url:"functions_func.html",children:[
{text:"a",url:"functions_func.html#index_a"},
{text:"b",url:"functions_func_b.html#index_b"},
{text:"c",url:"functions_func_c.html#index_c"},
{text:"d",url:"functions_func_d.html#index_d"},
{text:"e",url:"functions_func_e.html#index_e"},
{text:"f",url:"functions_func_f.html#index_f"},
{text:"g",url:"functions_func_g.html#index_g"},
{text:"h",url:"functions_func_h.html#index_h"},
{text:"i",url:"functions_func_i.html#index_i"},
{text:"l",url:"functions_func_l.html#index_l"},
{text:"m",url:"functions_func_m.html#index_m"},
{text:"n",url:"functions_func_n.html#index_n"},
{text:"o",url:"functions_func_o.html#index_o"},
{text:"p",url:"functions_func_p.html#index_p"},
{text:"r",url:"functions_func_r.html#index_r"},
{text:"s",url:"functions_func_s.html#index_s"},
{text:"t",url:"functions_func_t.html#index_t"},
{text:"u",url:"functions_func_u.html#index_u"},
{text:"v",url:"functions_func_v.html#index_v"},
{text:"w",url:"functions_func_w.html#index_w"},
{text:"x",url:"functions_func_x.html#index_x"},
{text:"y",url:"functions_func_y.html#index_y"},
{text:"z",url:"functions_func_z.html#index_z"}]},
{text:"Properties",url:"functions_prop.html",children:[
{text:"_",url:"functions_prop.html#index__5F"},
{text:"a",url:"functions_prop_a.html#index_a"},
{text:"b",url:"functions_prop_b.html#index_b"},
{text:"c",url:"functions_prop_c.html#index_c"},
{text:"d",url:"functions_prop_d.html#index_d"},
{text:"e",url:"functions_prop_e.html#index_e"},
{text:"f",url:"functions_prop_f.html#index_f"},
{text:"g",url:"functions_prop_g.html#index_g"},
{text:"h",url:"functions_prop_h.html#index_h"},
{text:"i",url:"functions_prop_i.html#index_i"},
{text:"j",url:"functions_prop_j.html#index_j"},
{text:"k",url:"functions_prop_k.html#index_k"},
{text:"l",url:"functions_prop_l.html#index_l"},
{text:"m",url:"functions_prop_m.html#index_m"},
{text:"n",url:"functions_prop_n.html#index_n"},
{text:"o",url:"functions_prop_o.html#index_o"},
{text:"p",url:"functions_prop_p.html#index_p"},
{text:"q",url:"functions_prop_q.html#index_q"},
{text:"r",url:"functions_prop_r.html#index_r"},
{text:"s",url:"functions_prop_s.html#index_s"},
{text:"t",url:"functions_prop_t.html#index_t"},
{text:"u",url:"functions_prop_u.html#index_u"},
{text:"v",url:"functions_prop_v.html#index_v"},
{text:"w",url:"functions_prop_w.html#index_w"},
{text:"x",url:"functions_prop_x.html#index_x"},
{text:"y",url:"functions_prop_y.html#index_y"},
{text:"z",url:"functions_prop_z.html#index_z"}]},
{text:"Events",url:"functions_evnt.html"}]}]},
{text:"Examples",url:"de/ddf/page_exov.html",children:[
{text:"Example 01: New File and QuickFocus",url:"d2/d5b/page_ex01.html",children:[
{text:"C#",url:"dd/dc0/page_ex01_cs.html"},
{text:"C++",url:"d6/d91/page_ex01_cpp.html"},
{text:"Mathematica",url:"d5/d31/page_ex01_nb.html"},
{text:"Matlab",url:"da/d4d/page_ex01_m.html"},
{text:"Python",url:"d2/de2/page_ex01_py.html"}]},
{text:"Example 02: NSC Ray Trace",url:"dc/d80/page_ex02.html",children:[
{text:"C#",url:"dd/d0b/page_ex02_cs.html"},
{text:"C++",url:"d5/d2e/page_ex02_cpp.html"},
{text:"Mathematica",url:"d1/db3/page_ex02_nb.html"},
{text:"Matlab",url:"d4/dd6/page_ex02_m.html"},
{text:"Python",url:"d2/d70/page_ex02_py.html"}]},
{text:"Example 03: Open File and Optimize",url:"d8/d0a/page_ex03.html",children:[
{text:"C#",url:"dc/d94/page_ex03_cs.html"},
{text:"C++",url:"d9/d94/page_ex03_cpp.html"},
{text:"Mathematica",url:"d1/d09/page_ex03_nb.html"},
{text:"Matlab",url:"df/d5b/page_ex03_m.html"},
{text:"Python",url:"dc/dc8/page_ex03_py.html"}]},
{text:"Example 04: Retrieve Data from FFT MTF",url:"d4/df2/page_ex04.html",children:[
{text:"C#",url:"db/dee/page_ex04_cs.html"},
{text:"C++",url:"d4/d56/page_ex04_cpp.html"},
{text:"Mathematica",url:"d8/d86/page_ex04_nb.html"},
{text:"Matlab",url:"df/dd7/page_ex04_m.html"},
{text:"Python",url:"da/def/page_ex04_py.html"}]},
{text:"Example 05: Parsing a ZRD File",url:"de/dec/page_ex05.html",children:[
{text:"C#",url:"db/d14/page_ex05_cs.html"},
{text:"C++",url:"d6/da8/page_ex05_cpp.html"},
{text:"Mathematica",url:"dc/da8/page_ex05_nb.html"},
{text:"Matlab",url:"d4/d66/page_ex05_m.html"},
{text:"Python",url:"de/d58/page_ex05_py.html"}]},
{text:"Example 06: NSC Phase",url:"d1/df1/page_ex06.html",children:[
{text:"C#",url:"dc/d3e/page_ex06_cs.html"},
{text:"C++",url:"d9/ddf/page_ex06_cpp.html"},
{text:"Matlab",url:"d7/d4f/page_ex06_m.html"},
{text:"Python",url:"d1/d62/page_ex06_py.html"}]},
{text:"Example 07: Tilt and Decenter Elements",url:"d0/dd1/page_ex07.html",children:[
{text:"C#",url:"db/d95/page_ex07_cs.html"},
{text:"C++",url:"db/df9/page_ex07_cpp.html"},
{text:"Matlab",url:"d3/de3/page_ex07_m.html"},
{text:"Python",url:"d7/d97/page_ex07_py.html"}]},
{text:"Example 08: NCE Detector Data ",url:"da/dc6/page_ex08.html",children:[
{text:"C#",url:"d5/dfd/page_ex08_cs.html"},
{text:"C++",url:"d8/de3/page_ex08_cpp.html"},
{text:"Matlab",url:"d9/d4a/page_ex08_m.html"},
{text:"Python",url:"df/d2e/page_ex08_py.html"}]},
{text:"Example 09: NSC CAD",url:"df/d81/page_ex09.html",children:[
{text:"C#",url:"d6/dc2/page_ex09_cs.html"},
{text:"C++",url:"d9/d9f/page_ex09_cpp.html"},
{text:"Matlab",url:"de/dab/page_ex09_m.html"},
{text:"Python",url:"d0/d8e/page_ex09_py.html"}]},
{text:"Example 10: NSC ZRD Filter String",url:"d7/d1f/page_ex10.html",children:[
{text:"C#",url:"d8/d98/page_ex10_cs.html"},
{text:"C++",url:"d7/d47/page_ex10_cpp.html"},
{text:"Matlab",url:"d6/dfc/page_ex10_m.html"},
{text:"Python",url:"d7/d57/page_ex10_py.html"}]},
{text:"Example 11: Basic Sequential",url:"d4/d3e/page_ex11.html",children:[
{text:"C#",url:"d1/d84/page_ex11_cs.html"},
{text:"C++",url:"d4/d01/page_ex11_cpp.html"},
{text:"Matlab",url:"de/d40/page_ex11_m.html"},
{text:"Python",url:"d9/d42/page_ex11_py.html"}]},
{text:"Example 12: Sequential System Explorer",url:"db/d5d/page_ex12.html",children:[
{text:"C#",url:"d8/dc8/page_ex12_cs.html"},
{text:"C++",url:"dd/da6/page_ex12_cpp.html"},
{text:"Matlab",url:"d5/dfc/page_ex12_m.html"},
{text:"Python",url:"db/d11/page_ex12_py.html"}]},
{text:"Example 14: Sequential Tolerance",url:"d7/dc1/page_ex14.html",children:[
{text:"C#",url:"d9/d1c/page_ex15_cs.html"},
{text:"C++",url:"df/d85/page_ex15_cpp.html"},
{text:"Matlab",url:"d6/d5a/page_ex15_m.html"},
{text:"Python",url:"d7/d76/page_ex15_py.html"}]},
{text:"Example 15: Sequential Optimization",url:"d9/d37/page_ex15.html",children:[
{text:"C#",url:"d9/d1c/page_ex15_cs.html"},
{text:"C++",url:"df/d85/page_ex15_cpp.html"},
{text:"Matlab",url:"d6/d5a/page_ex15_m.html"},
{text:"Python",url:"d7/d76/page_ex15_py.html"}]},
{text:"Example 16: User-Defined Operand (UDOC)",url:"d5/d36/page_ex16.html",children:[
{text:"C#",url:"de/da2/page_ex16_cs.html"},
{text:"C++",url:"d4/d65/page_ex16_cpp.html"}]},
{text:"Example 17: Bulk Scatter",url:"dc/da1/page_ex17.html",children:[
{text:"C#",url:"d1/d06/page_ex17_cs.html"},
{text:"C++",url:"d1/d91/page_ex17_cpp.html"},
{text:"Matlab",url:"d8/d3b/page_ex17_m.html"},
{text:"Python",url:"da/df7/page_ex17_py.html"}]},
{text:"Example 18: Multiple Configurations",url:"dd/d6f/page_ex18.html",children:[
{text:"C#",url:"d5/d52/page_ex18_cs.html"},
{text:"C++",url:"d9/d8e/page_ex18_cpp.html"},
{text:"Matlab",url:"da/d54/page_ex18_m.html"},
{text:"Python",url:"da/d16/page_ex18_py.html"}]},
{text:"Example 19: Surface Properties",url:"db/d2e/page_ex19.html",children:[
{text:"C#",url:"da/d39/page_ex19_cs.html"},
{text:"C++",url:"db/d63/page_ex19_cpp.html"},
{text:"Matlab",url:"df/de2/page_ex19_m.html"},
{text:"Python",url:"d9/d48/page_ex19_py.html"}]},
{text:"Example 20: Exporting as CAD File",url:"dd/dd2/page_ex20.html",children:[
{text:"C#",url:"d3/d39/page_ex20_cs.html"},
{text:"C++",url:"d8/da8/page_ex20_cpp.html"},
{text:"Matlab",url:"d9/d7e/page_ex20_m.html"},
{text:"Python",url:"d0/de2/page_ex20_py.html"}]},
{text:"Example 21: White LED Phosphor",url:"d5/dce/page_ex21.html",children:[
{text:"C#",url:"d9/d49/page_ex21_cs.html"},
{text:"C++",url:"d1/dd1/page_ex21_cpp.html"},
{text:"Matlab",url:"de/d0b/page_ex21_m.html"},
{text:"Python",url:"d5/d75/page_ex21_py.html"}]},
{text:"Example 22: Sequential Analysis",url:"d8/d2d/page_ex22.html",children:[
{text:"C#",url:"de/d09/page_ex22_cs.html"},
{text:"C++",url:"de/d7f/page_ex22_cpp.html"},
{text:"Mathematica",url:"db/dd9/page_ex22_nb.html"},
{text:"Matlab",url:"dc/d7e/page_ex22_m.html"},
{text:"Python",url:"dd/dc2/page_ex22_py.html"}]},
{text:"Example 23: Ray Fan User Analysis",url:"da/d60/page_ex23.html",children:[
{text:"C#",url:"df/df9/page_ex23_cs.html"},
{text:"C++",url:"df/d48/page_ex23_cpp.html"},
{text:"Matlab",url:"d1/d6b/page_ex23_m.html"},
{text:"Python",url:"d6/db8/page_ex23_py.html"}]},
{text:"Example 24: Non-Sequential Detector Data",url:"d0/d46/page_ex24.html",children:[
{text:"C#",url:"d9/db5/page_ex24_cs.html"},
{text:"C++",url:"d3/d44/page_ex24_cpp.html"},
{text:"Matlab",url:"d6/da1/page_ex24_m.html"},
{text:"Python",url:"da/daa/page_ex24_py.html"}]},
{text:"Example 25: Source Spectrum Diffraction Grating",url:"d4/d4e/page_ex25.html",children:[
{text:"C#",url:"d7/d49/page_ex25_cs.html"},
{text:"C++",url:"df/d8b/page_ex25_cpp.html"},
{text:"Matlab",url:"da/d26/page_ex25_m.html"},
{text:"Python",url:"d6/da3/page_ex25_py.html"}]},
{text:"Example 26: Modify Project Preferences",url:"de/d32/page_ex26.html",children:[
{text:"C#",url:"d7/d84/page_ex26_cs.html"},
{text:"C++",url:"d4/d92/page_ex26_cpp.html"},
{text:"Matlab",url:"df/d60/page_ex26_m.html"},
{text:"Python",url:"d5/d0d/page_ex26_py.html"}]}]}]}
